### ISSUE TITLE
Paper and corresponding codes

### ISSUE THREAD

**Issue by ChengjunJia** [DINT-NSDI24/DINT#1]
In the paper, about the lock manager:

> To resolve such possible deadlocks, DINT lets the lock manager check if any two exclusive lock acquiring operations on the same lock state come from the same transaction client, by maintaining a holder client ID (e.g., IP and port pair) for each exclusive lock; if so, the lock manager directly returns a locking success message.

But I have not found the related codes in the repository. Would you mind to tell me where it is? Especially, which demo?

**Comment by xyxiang7** [comment]
Hi,

We did not implement this mechanism because such deadlocks theoretically never occur in any of our benchmarks. However, implementing it is straightforward: you would need to add a BPF map in the servers with the same number of entries as the number of exclusive locks, with each entry corresponding to a client ID indicating the client holding the respective lock.

**Comment by ChengjunJia** [comment]
Good~
Thanks
